# Generated by Django 4.2 on 2024-12-15 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.TextField(default="Default Project")),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(default="Default Task")),
                (
                    "priority",
                    models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0
                    ),
                ),
                ("description", models.TextField()),
                ("is_daily_task", models.BooleanField(default=False)),
                ("deadline", models.DateField(null=True)),
                ("calendar_linked_date", models.DateField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_task",
                        to="task_manager.project",
                    ),
                ),
            ],
        ),
    ]
