# Generated by Django 4.2 on 2025-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="name",
            field=models.TextField(default="Default Project"),
        ),
        migrations.AlterUniqueTogether(
            name="projecttask",
            unique_together={("project", "title")},
        ),
    ]
